[build-system]
requires = ["setuptools>=80.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "media-downloader"
version = "2.1.36"
description = "Download audio/videos from the internet!\nHost an MCP Server for Agentic AI to download videos!"
readme = "README.md"
authors = [{ name = "Audel Rouhi", email = "knucklessg1@gmail.com" }]
license = { text = "MIT" }
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: Public Domain",
    "Environment :: Console",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.10"
dependencies = [
    "yt-dlp[default]>=2025.12.08",
]

[project.optional-dependencies]
mcp = [
    "fastmcp>=3.0.0b1",
    "eunomia-mcp>=0.3.10",
    "fastapi>=0.128.0"
]
a2a = [
    "pydantic-ai-slim[fastmcp,openai,anthropic,google,huggingface,a2a,ag-ui,web]>=1.32.0",
    "pydantic-ai-skills",
    "fastapi>=0.128.0"
]
all = [
    "fastmcp>=3.0.0b1",
    "eunomia-mcp>=0.3.10",
    "pydantic-ai-slim[fastmcp,openai,anthropic,google,huggingface,a2a,ag-ui,web]>=1.32.0",
    "pydantic-ai-skills",
    "fastapi>=0.128.0"
]

[project.scripts]
media-downloader = "media_downloader.media_downloader:media_downloader"
media-downloader-mcp = "media_downloader.media_downloader_mcp:media_downloader_mcp"
media-downloader-agent = "media_downloader.media_downloader_agent:agent_server"

[tool.setuptools.package-data]
media_downloader = ["mcp_config.json", "skills/**"]

[tool.setuptools.packages.find]
where = ["."]
